### ISSUE TITLE
Add summary

### ISSUE THREAD

**Issue by maruloop** [reviewdog/action-terraform-validate#17]
Now we use the `detail` field as a comment in https://github.com/reviewdog/action-terraform-validate/blob/main/entrypoint.sh#L14.
However, 'detail' is an optional field, so we should add the `summary` field as well.

summary:
https://developer.hashicorp.com/terraform/cli/commands/validate#summary
detail:
https://developer.hashicorp.com/terraform/cli/commands/validate#detail

**Comment by buzztaiki** [comment]
I use following script to convert terraform validate result to rdjsonl

```
jq_script='
.diagnostics[]
| {
  severity: (.severity|ascii_upcase),
  message: "\(.summary)\n\(.detail)",
  location: {
    path: .range.filename,
    range: {
      start: (.range.start|{line, column}),
      end: (.range.end|{line, column})},
    },
}
'

terraform validate -json | jq "$jq_script" -c
```
