### ISSUE TITLE
Terraform version not passed to build

### ISSUE THREAD

**Issue by buker** [reviewdog/action-terraform-validate#21]
I want a different version of terraform, but terraform_version input is not working because in DockerFile it is set up by ENV and not ARG which means input is not passed to docker build.

**Comment by maruloop** [comment]
Thank you for opening an issue.
I will fix it later (perhaps in this week)

**Comment by buker** [comment]
If you want I can make or with fix.

**Comment by maruloop** [comment]
Thank you! Could you submit a PR?

**Comment by maruloop** [comment]
Thank you! let me close this issue.

**Comment by maruloop** [comment]
I found this opened issue now.
https://github.com/orgs/community/discussions/25241

Let me consider how I can take a workaround.
